#!/bin/bash

# SVTGet v0.1.1 (fork by DomeDan 2012-03-03)
# Updates can be found at http://svtget.se/
# Support the project with Flattr: https://flattr.com/thing/300374/SVT-Get-a-local-cache-tool-for-SVT-Play
#
# Description: The script can download the RTMP streams available from the
# online streaming service "SVT Play", managed by Sveriges Television
#
# Original author: Mikael "MMN-o" Nordfeldth
# License: GPLv3
# http://www.gnu.org/licenses/gpl-3.0.txt
#
# URL: http://blog.mmn-o.se/
# Flattr: https://flattr.com/thing/188162/MMN-o-on-Flattr

# Changelog:
# -- v0.1.1
#    * deb package created by sikevux, small fixes on other stuff
# -- v0.1
#    * Initial functionality. Normal links seem to be working.

# Sample usage:
# ./svtget http://svtplay.se/v/2440756/k_special/presspauseplay

DEPENDENCIES="rtmpdump curl sed cut bash"
for DEP in $DEPENDENCIES; do
	if [ -z "`which $DEP`" ]; then
		echo "ERROR: Missing dependency '$DEP'." >&2
		exit
	fi
done

# Available bitrates: 320 850 1400 2400
BITRATE=""
function set_bitrate {
	case $1 in
	l)	BITRATE=320	;;
	m)	BITRATE=850	;;
	n)	BITRATE=1400	;;
	h)	BITRATE=2400	;;
	320|850|1400|2400)
		BITRATE=$1	;;
	*)
		echo "Bad quality setting ($1), keeping setting '$BITRATE'"
		;;
	esac
}

function get_tcUrls {
	local html=$1
	local bitrate=$2
	expr "$bitrate" + 1 &> /dev/null
	if [ $? -gt 0 ] || [ -z "$bitrate" ] || [ "$bitrate" -eq 0 ]; then
		bitrate='[0-9]\+'
	fi
	echo $html | sed "s/\(rtmp[e]\?:[^|&]*\),bitrate:\($bitrate\)/\\n\2|\1\\n/g" | grep -E '^[[:digit:]]+\|' | sort -n | uniq 
}

function get_tcUrls_oa {
	local html=$1
	echo $html | sed "s/\(rtmp[e]\?:[^|&]*\)&amp;/\\n320|\1\\n/g" | grep -E '^[[:digit:]]+\|' | sort -n | uniq 
}

function get_sub {
	local html=$1
	echo -ne "\nwant subtitle? [y/n] "
	read ask_sub
	if [ -n "$ask_sub" ] && [ "y" == "$ask_sub" ]; then
		subUrl=`echo $html | sed "s/subtitle\=\(http:[^|&]*\)\&amp/\\n\-\-sub\-file \1\\n/g"| grep "\-\-sub\-file " | uniq` 
	fi
}

function pick_tcUrl {
	echo "#  Bitrate	Stream name" >&2
	let n=1
	for STREAM in $@; do
		local BITRATE=`echo $STREAM | cut -d '|' -f 1 -`
		Streams[$n]=`echo $STREAM | cut -d '|' -f 2 -`
		local NAME=`basename $STREAM`
		echo "$n. ${BITRATE} kbps	$NAME" >&2
		let n++
	done
	
	stream=0
	if [ "$#" -eq 1 ]; then
		stream=1
	fi
	while [ -z ${Streams[$stream]} ]; do
		echo -ne "\nWhich file do you want? [#] "
		read stream
		if [ -n "$stream" ] && [ "q" == "$stream" ]; then
			exit
		fi
	done
	tcUrl=${Streams[$stream]}
}

while getopts "q:" opt; do
	case $opt in
	q)
		set_bitrate $OPTARG
		;;
	\?)
		echo "invalid option: -$OPTARG" >&2
		exit 1
		;;
	esac
done

pageUrl=${!#}
if [ -z "$pageUrl" ]; then
	echo "Usage: $0 [-q l|m|n|h] http://svtplay.se/v/..." >&2
	exit 1
fi

if [[ ! "$pageUrl" =~ http://svtplay.se ]]; then
	echo "Bad URL. Not SVT Play?" >&2
	exit 1
fi

HTML=`curl -s "$pageUrl"`
swfUrl="http://svtplay.se$(echo $HTML | sed 's/.*x-shockwave-flash" data="\([^"]\+\)\".*/\1/')"
tcUrls=$(get_tcUrls "$HTML" "$BITRATE")
if [ -z "$tcUrls" ]; then
tcUrls=$(get_tcUrls_oa "$HTML" )
	get_tcUrls_oa "$HTML"
	if [ -z "$tcUrls" ]; then
		echo "ERROR: No rtmp streams found. No clip in that quality?
Please visit http://svtget.se/ for updates and information. If the website's down, use a search engine to find copies." >&2
		exit 1
	fi
fi

pick_tcUrl $tcUrls

extension="mp4"
if [ "$extension" != "${tcUrl##*.}" ]; then
	extension="flv"
fi
filename="$(basename $pageUrl).$extension"
prefix="$(basename $(dirname $pageUrl))"
if echo "$prefix" | grep -qE '[^0-9]+' ; then
  filename="${prefix}_${filename}"
fi

get_sub "$HTML"

echo -ne "\nDo you want to view i vlc or save to file? [v/f] "
read ask_vlc
if [ -n "$ask_vlc" ] && [ "v" == "$ask_vlc" ]; then
	rtmpdump -r "$tcUrl" --swfVfy="$swfUrl" -o - | vlc - $subUrl
elif [ -n "$ask_vlc" ] && [ "f" == "$ask_vlc" ]; then
	echo Running RTMPDump for "$tcUrl" and saving to "$filename"
	#rtmpdump -r "$tcUrl" --swfVfy="$swfUrl" -o "$filename"
	if [ -n "$subUrl" ]; then
		subUrl=`echo "$subUrl" | sed 's/\-\-sub\-file //g'`
		sub_filename="$(basename $pageUrl).srt"
		echo " and subtitle to: "$sub_filename
		wget $subUrl -O $sub_filename
	fi
fi